title: Mojo가 모조
description: Mojo를 기초부터 배워봅시다
url: https://kojunseo.github.io # the base hostname & protocol for your site, e.g. http://example.com

# repository: just-the-docs/just-the-docs # for github-metadata
# theme: just-the-docs

aux_links:
  "Youtube 강의":
    - "https://www.youtube.com/channel/UCCaunu3Cv09ZCDxU13Gx3Hg"

enable_copy_code_button: true

footer_content: "Copyright &copy; 2023 Junseo Ko. 본 강의자료와 영상은 Mojo도큐먼트를 직접분석하여 작성하였습니다. \n무단 복제와 본 내용을 퍼가서 새로운 컨텐츠로 제작하는 것을 엄격히 금지합니다. \n문의: piglets.frizzle0v@icloud.com"
